### PR TITLE
[screensaver] update after upstream merge

### PR DESCRIPTION
**Pull request by AlwinEsch**
This cleanup the screensaver class to match standard, remove possible memleaks and reduce amount of process work.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Has been tested with binary and python add-on's. Stupid that python need this with `CAddonDll`, becomes improved soon.

**Comment by AlwinEsch** [comment]
Also maybe good for the xbmc repo? What think you @FernetMenta ?

**Comment by FernetMenta** [comment]
@AlwinEsch yes it is.

**Comment by AlwinEsch** [comment]
Opened request https://github.com/xbmc/xbmc/pull/11238, after they come in becomes this cleaned up (set of the new `Stop()` from request before).

**Comment by AlwinEsch** [comment]
Is in xbmc

**Comment by FernetMenta** [comment]
top

**Pull request merged**
