### PR TITLE
[addons] change image decoder to new way

### PR DESCRIPTION
**Pull request by AlwinEsch**
This changes the image decoder addon to the new way.

Some parts e.g. extensions need a improve in future.

The addon here is updated to them: https://github.com/AlwinEsch/imagedecoder.raw/blob/kodi-agile/src/RawPicture.cpp

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Hi @notspiff here are the changes for your Image Decoder system.

There are parts from my changes who I'm not like, but hard to become it better on reworked system.
Mean like this:
```cpp
std::string CAdvancedSettings::GetPictureExtensions() const
{
  std::string result(m_pictureExtensions);

  for (const auto& addonInfo : CAddonMgr::GetInstance().GetAddonInfos(true, ADDON_IMAGEDECODER))
  {
    result += '|';
    result += addonInfo->Type(ADDON_IMAGEDECODER)->GetValue("@extension").asString();
  }

  return result;
}
```

With the `addonInfo->Type(ADDON_IMAGEDECODER)->GetValue("@extension").asString()` is easy, but for me is bad to have the `"@extension"` string who is related to addon type outside of the class CImageDecoder. But want to prevent a class creation only for check of a value.

What think you about the way to get addon.xml values? This values are stored on AddonManager since the cpluff is no more present.

**Comment by AlwinEsch** [comment]
@notspiff has seen your add-on was nearly on the new way what I planned :-D and was nearly nothing needed to replace.

**Comment by notspiff** [comment]
good. i did model it on the state of things in master so i'm not surprised :)

can't the parameters be backed by a general key-value store on the CAddon level? that way no cast would be necessary. also  i'd drop the cpluff-ism of the @ prefix.

**Comment by AlwinEsch** [comment]
Goal from me was to create CAddon only if it do anything, but can be still done with the old way.

With the `@` comes from a on xml defined value with `<xyz value="1"/>, for this then `@value` on the first or if the xml is child from another as `xyz@value`. If it comes as `<xyz>1</xyz> then the value name is `xyz` without the `@`, this style was for me good on cpluff to different the value place.

**Pull request merged**
