### PR TITLE
[addons] change binary addon version check way

### PR DESCRIPTION
**Pull request by AlwinEsch**
This remove complete the use of `C` functions for version checks of different add-on types.

The versions are now checked always from the xml. This way is required to hold `CAddonDll` independent from related types.

With the old way was always only one instance type possible on add-on. The other of this change is to prevent not needed dll loads. Before was a loaded dll required to check them, as long it was only one instance, was it OK, but to handle the different types together is it for better to do before load.

Add-ons need only a recompile and if comes in earlier to xbmc can be several functions from addons removed.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@FernetMenta is this also for you OK?

It use now only the:
- ./addons/xbmc.addon//addon.xml
- ./addons/xbmc.audioencoder/addon.xml
- ./addons/xbmc.codec/addon.xml
- ./addons/xbmc.gui/addon.xml
- ./addons/xbmc.pvr/addon.xml
- ./addons/kodi.adsp/addon.xml
- ./addons/kodi.audiodecoder/addon.xml
- ./addons/kodi.game/addon.xml
- ./addons/kodi.guilib/addon.xml
- ./addons/kodi.inputstream/addon.xml
- ./addons/kodi.peripheral/addon.xml

With the values defined here on addons (here from pvr.vdr.vnsi) itself:
```xml
  <requires>
    <c-pluff version="0.1"/>
    <import addon="xbmc.pvr" version="5.2.1"/>
    <import addon="xbmc.codec" version="1.0.1"/>
    <import addon="kodi.guilib" version="5.10.0"/>
  </requires>
```

**Comment by FernetMenta** [comment]
I would do it the other way raounf and move away from the cpluff/xml crap. This never worked reliable and cpluff is imo not suited for binary addons.
Version has to be compiled into the binary. Only this provides correct information about the version the addon was compiled against.

**Comment by FernetMenta** [comment]
@AlwinEsch did you look into inputstream addon and how it handles versions?

**Comment by AlwinEsch** [comment]
The input stream use it nearly like pvr, but without min version.

Here the code styled version part of my rework https://github.com/FernetMenta/kodi-agile/blob/add-addon-instance-handling/xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h
This use a special header for all versions together. Is to prevent conflicts during code changes of them and hold it small as possible.

I look now to bring this in a bit earlier and go complete away from this xml way.

**Comment by AlwinEsch** [comment]
Ah forgot :) Thanks a lot!

**Comment by AlwinEsch** [comment]
Tried to add the versions.h and is a bit a Hen and egg problem with use of a `inline`. Need to come in together with the rest.

For this becomes it closed.

**Pull request closed without merging**
