### PR TITLE
[win][wip] fix windows depends buildsystem

### PR DESCRIPTION
**Pull request by AchimTuran**

### CODE REVIEW

**Comment by AchimTuran** [comment]
@peak3d @fritsch @FernetMenta 
the windows build seems now to be fine.

Can I merge this PR?

**Comment by FernetMenta** [comment]
where is this code from? I can't find any windows build system patches on the vpupdates branch

**Comment by hudokkow** [comment]
https://github.com/xbmc/xbmc/pull/12031

**Comment by FernetMenta** [comment]
then we should keep the original commits. @AchimTuran we get those anywhy on next merge of master

**Comment by AchimTuran** [comment]
The please do a merge.

**Pull request closed without merging**
