### PR TITLE
VideoPlayer: ffmpeg upgrade and rework

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by AchimTuran** [comment]
@fritsch @FernetMenta 
How to you build kodi-agile with ffmpeg 3.2? On my Linux system it doesn't download it from https://github.com/xbmc/FFmpeg/archive/release/3.2-xbmc.tar.gz, because the release is not yet published :-)

**Comment by FernetMenta** [comment]
strange, when I click on this link, it starts download

**Comment by AchimTuran** [comment]
I got this error message after make:
-- downloading...
       src='https://github.com/xbmc/FFmpeg/archive/release/3.2-xbmc.tar.gz'
       dst='/home/swissknife/projects/linux/kodi/build/build_kodi-agile_adsp_v2/build/download/ffmpeg-release/3.2-xbmc.tar.gz'
       timeout='none'
error: downloading 'https://github.com/xbmc/FFmpeg/archive/release/3.2-xbmc.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
-- Retry after 60 seconds (attempt #5) ...
-- downloading...
       src='https://github.com/xbmc/libdvdcss/archive/master.tar.gz'
       dst='/home/swissknife/projects/linux/kodi/build/build_kodi-agile_adsp_v2/build/download/libdvdcss-master.tar.gz'
       timeout='none'
error: downloading 'https://github.com/xbmc/libdvdcss/archive/master.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
-- Retry after 60 seconds (attempt #5) ...
-- downloading...
       src='https://github.com/xbmc/FFmpeg/archive/release/3.2-xbmc.tar.gz'
       dst='/home/swissknife/projects/linux/kodi/build/build_kodi-agile_adsp_v2/build/download/ffmpeg-release/3.2-xbmc.tar.gz'
       timeout='none'
error: downloading 'https://github.com/xbmc/FFmpeg/archive/release/3.2-xbmc.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
CMake Error at ffmpeg-stamp/download-ffmpeg.cmake:161 (message):
  Downloading failed


CMakeFiles/ffmpeg.dir/build.make:89: recipe for target 'build/ffmpeg/src/ffmpeg-stamp/ffmpeg-download' failed
make[2]: *** [build/ffmpeg/src/ffmpeg-stamp/ffmpeg-download] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/ffmpeg.dir/all' failed
make[1]: *** [CMakeFiles/ffmpeg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- downloading...
       src='https://github.com/xbmc/libdvdcss/archive/master.tar.gz'
       dst='/home/swissknife/projects/linux/kodi/build/build_kodi-agile_adsp_v2/build/download/libdvdcss-master.tar.gz'
       timeout='none'
error: downloading 'https://github.com/xbmc/libdvdcss/archive/master.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
CMake Error at dvdcss-stamp/download-dvdcss.cmake:161 (message):
  Downloading failed

**Comment by AchimTuran** [comment]
strange...

My old branch from xbmc has the same issue

**Pull request merged**
